### ISSUE TITLE
Transform for-of/for-in to normal for

### ISSUE THREAD

**Issue by aminya** [sapphi-red/ts-transformer-for-of#1]
Option for transforming `for..of` / `for..in` when targetting ES6 and above.

----

Based on my investigation,  `for..of` / `for..in` loops are slower than the traditional `for` loops (see the result: https://github.com/aminya/TypeScript-optimization)

It is pretty funny that when I target ES5, TypeScript converts `for..of` to the traditional loops, which makes the code faster, but I cannot do this when I target anything above ES6. 

I noticed that there is `"downlevelIteration"` which does the opposite of what I want.

## Use Cases

It enhances the performance but allows us to write readable code.

## Examples

```typescript
// for - in
  let sum = 0
  for (const i in arr) {
    sum += arr[i]
  }

// for - of
  let sum = 0
  for (const a of arr) {
    sum += a
  }

// should both be transformed to:
// Traditional
  let sum = 0
  for (let i = 0, l = arr.length; i < l; ++i) {
    sum += arr[i]
  }

// or
  let sum = 0
  for (let i = 0, l = arr.length; i < l; ++i) {
    let a = arr[i]
    sum += a
  }
```

**Comment by sapphi-red** [comment]
I've released v0.5.0 that includes a change to transform `for-of` into traditional `for` only when it is Array.
I didn't add any options to disable this because I didn't feel it is necessary.

Whatever the target is set (`ES5`, `ES2015` etc.), it will transform them like below.

```ts
for (const v of arr) {
  console.log(v)
}
```

```js
for (let _i = 0; _i < arr.length; _i++) {
    const v = arr[_i];
    console.log(v);
}
```

I didn't make it transform `for..in` into `for` because `for..in` should not be used for Arrays and their behaviors differs from `for..of` (There's no way to statically check whether a property is added to Array.prototype).

**Comment by aminya** [comment]
Thank you for doing this! Just a minor thing: 

Could you make `arr.length` a variable instead of looking it up every time in the for the head?

If we could make the for-loop like (see `l = arr.length`)

> ```js
> for (let _i = 0, _l = arr.length; _i < _l; _i++) {
>     const v = arr[_i];
>     console.log(v);
> }
> ```
rather

> ```js
> for (let _i = 0; _i < arr.length; _i++) {
>     const v = arr[_i];
>     console.log(v);
> }
> ```
> 
 
It would be better. 

# Rationale:

[looping over dom nodes](https://jsperf.com/testing-loops-over-dom-nodes) shows that doing this is much faster (X20). 

In [my benchmarks](https://github.com/aminya/TypeScript-optimization#traditional-for-optimization) that I looped over a simple numeric array, I couldn't see any performance difference for doing this. Probably looking up `arr.length` is as fast as looking up `l` from memory for simple numeric arrays.

However considering the first benchmark, it seems like a more reasonable code anyways.

The only limitation of doing so is that the transformation will not work for those loops whose array length changes inside them, which may not be relevant anyways since I think `for-of` assumes that the array length doesn't change. 

Let me know what you think.

**Comment by sapphi-red** [comment]
I tested some behaviors when push elements within a loop.

When I did it with `Array::forEach`, the equivalent statement is the following code. It worked as if the length is a constant.

```js
const arr = [0,1,2]
arr.forEach((v, i, arr) => {
  if (i < 2) {
    arr.push(3)
  }
  console.log('  []: ', v)
})
```

```js
const arr = [0,1,2]
let i = 0
for (let j = 0, len = arr.length; j < len; j++) {
  const v = arr[j]
  if (i < 2) {
    arr.push(3)
    i++
  }
  console.log('  []: ', v)
}
```

```plaintext
   []:  0
   []:  1
   []:  2
```

However, when I did it with `for-of` loop, the length was mutable.

```js
const arr = [0,1,2]
let i = 0
for (const v of arr) {
  if (i < 2) {
    arr.push(3)
    i++
  }
  console.log('  []: ', v)
}
```

```js
const arr = [0,1,2]
let i = 0
for (let j = 0; j < arr.length; j++) {
  const v = arr[j]
  if (i < 2) {
    arr.push(3)
    i++
  }
  console.log('  []: ', v)
}
```

```plaintext
   []:  0
   []:  1
   []:  2
   []:  3
```

So I will only change it with Array iteration methods. Because I don't want to make this transformer to break any codes as much as possible.

---

For now, I am only targeting to Arrays and this transformer only transforms Arrays.
In the future, I may support NodeLists and HTMLCollection.
